version: '3'
services:
  webhook-bot:
    build:
      context: .
    ports:
      - "3005:80"
    volumes:
      - ./src:/app/src
    command:
      [
        "gunicorn",
        "wsgi:app",
        "--bind",
        "0.0.0.0:80",
        "--workers",
        "4"
      ]
